# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('secret_id', 'user_id')]),
        ),
    ]
